import { useState } from "react";
import Button from "./Button";

const BASE_URL = import.meta.env.VITE_API_URL || "https://splitease-99pt.onrender.com/api";

function fmtInr(n) {
  return `₹${Number(n).toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}
function fmtDate(d) {
  return new Date(d).toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" });
}

function buildPDF(data) {
  const { group, expenses, settlements } = data;

  const totalSpend   = expenses.reduce((s, e) => s + e.amount, 0);
  const totalSettled = settlements.filter((s) => s.status === "confirmed").reduce((s, p) => s + p.amount, 0);

  const rows = expenses.map((e) =>
    `<tr>
      <td>${fmtDate(e.date)}</td>
      <td>${e.title}</td>
      <td>${e.category || "Other"}</td>
      <td>${e.paidBy?.name || ""}</td>
      <td style="text-align:right;font-family:monospace">${fmtInr(e.amount)}</td>
      <td>${e.splitType} ÷ ${e.splits.length}</td>
    </tr>`
  ).join("");

  const settRows = settlements.map((s) =>
    `<tr>
      <td>${fmtDate(s.createdAt)}</td>
      <td>${s.fromUser?.name || ""}</td>
      <td>${s.toUser?.name || ""}</td>
      <td style="text-align:right;font-family:monospace">${fmtInr(s.amount)}</td>
      <td><span style="color:${s.status === "confirmed" ? "#2f9e58" : s.status === "rejected" ? "#d6543f" : "#e3992f"}">${s.status}</span></td>
    </tr>`
  ).join("");

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>SplitEase — ${group.name}</title>
<style>
  body{font-family:system-ui,sans-serif;padding:32px;color:#1a1a1a;max-width:900px;margin:auto}
  h1{font-size:24px;margin-bottom:4px}
  .meta{font-size:13px;color:#666;margin-bottom:24px}
  .summary{display:flex;gap:24px;margin-bottom:32px}
  .card{border:1px solid #e5e5e5;border-radius:12px;padding:16px 20px;min-width:160px}
  .card .label{font-size:11px;color:#666;margin-bottom:4px}
  .card .value{font-size:20px;font-weight:600;font-family:monospace}
  h2{font-size:16px;margin:32px 0 12px}
  table{width:100%;border-collapse:collapse;font-size:13px}
  th{text-align:left;padding:8px 12px;background:#f5f5f5;font-weight:600;border-bottom:2px solid #e5e5e5}
  td{padding:8px 12px;border-bottom:1px solid #f0f0f0}
  tr:last-child td{border-bottom:none}
  .footer{margin-top:40px;font-size:11px;color:#999;text-align:center}
  @media print{body{padding:16px}}
</style>
</head>
<body>
<h1>${group.name}</h1>
<div class="meta">
  ${group.groupType} · ${group.members.length} members · Exported ${fmtDate(new Date())}
</div>

<div class="summary">
  <div class="card"><div class="label">Total spend</div><div class="value">${fmtInr(totalSpend)}</div></div>
  <div class="card"><div class="label">Expenses</div><div class="value">${expenses.length}</div></div>
  <div class="card"><div class="label">Settled</div><div class="value">${fmtInr(totalSettled)}</div></div>
  <div class="card"><div class="label">Members</div><div class="value">${group.members.length}</div></div>
</div>

<h2>Expenses</h2>
<table>
  <thead><tr><th>Date</th><th>Title</th><th>Category</th><th>Paid By</th><th>Amount</th><th>Split</th></tr></thead>
  <tbody>${rows || "<tr><td colspan='6' style='color:#999'>No expenses</td></tr>"}</tbody>
</table>

<h2>Settlements</h2>
<table>
  <thead><tr><th>Date</th><th>From</th><th>To</th><th>Amount</th><th>Status</th></tr></thead>
  <tbody>${settRows || "<tr><td colspan='5' style='color:#999'>No settlements</td></tr>"}</tbody>
</table>

<div class="footer">Generated by SplitEase Stay · splitease-taupe.vercel.app</div>
</body>
</html>`;
}

export default function ExportPanel({ groupId }) {
  const [exporting, setExporting] = useState(null); // "csv" | "pdf" | null
  const [error, setError]         = useState("");

  const token = localStorage.getItem("token");

  const handleCSV = async () => {
    setExporting("csv"); setError("");
    try {
      const res = await fetch(`${BASE_URL}/groups/${groupId}/export/csv`, {
        headers: { Authorization: `Bearer ${token}` },
      });
      if (!res.ok) throw new Error("Export failed");
      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url; a.download = `splitease-${groupId}.csv`; a.click();
      URL.revokeObjectURL(url);
    } catch (e) {
      setError("CSV export failed. Try again.");
    } finally { setExporting(null); }
  };

  const handlePDF = async () => {
    setExporting("pdf"); setError("");
    try {
      const res = await fetch(`${BASE_URL}/groups/${groupId}/export/json`, {
        headers: { Authorization: `Bearer ${token}` },
      });
      if (!res.ok) throw new Error("Export failed");
      const data = await res.json();
      const html = buildPDF(data);
      const win = window.open("", "_blank");
      win.document.write(html);
      win.document.close();
      setTimeout(() => win.print(), 500);
    } catch (e) {
      setError("PDF export failed. Try again.");
    } finally { setExporting(null); }
  };

  return (
    <div>
      <h2 className="font-display text-lg font-semibold text-ink">Export</h2>
      <p className="mt-1 text-xs text-muted">Download all expenses, bills, and settlements for this group.</p>

      <div className="mt-4 grid grid-cols-2 gap-3">
        <button
          onClick={handleCSV}
          disabled={!!exporting}
          className="flex flex-col items-center gap-2 rounded-2xl border border-hairline bg-surface p-5 transition-colors hover:bg-paper-dim disabled:opacity-50"
        >
          <span className="text-3xl">📊</span>
          <span className="text-sm font-semibold text-ink">CSV</span>
          <span className="text-xs text-muted text-center">Open in Excel / Sheets</span>
          {exporting === "csv" && <span className="text-xs text-accent">Downloading…</span>}
        </button>

        <button
          onClick={handlePDF}
          disabled={!!exporting}
          className="flex flex-col items-center gap-2 rounded-2xl border border-hairline bg-surface p-5 transition-colors hover:bg-paper-dim disabled:opacity-50"
        >
          <span className="text-3xl">📄</span>
          <span className="text-sm font-semibold text-ink">PDF</span>
          <span className="text-xs text-muted text-center">Print or save as PDF</span>
          {exporting === "pdf" && <span className="text-xs text-accent">Generating…</span>}
        </button>
      </div>

      {error && <p className="mt-3 rounded-lg bg-danger-soft px-3 py-2 text-sm text-danger">{error}</p>}

      <p className="mt-4 text-xs text-muted">
        PDF opens a print dialog — choose "Save as PDF" in your browser's print options.
      </p>
    </div>
  );
}
